### ISSUE TITLE
ReferenceError: RQ is not defined - when running example

### ISSUE THREAD

**Issue by cheung31** [longseespace/qix#5]
### Current Behavior

When attempting to run examples: 
* `examples/WithRedux` via `yarn start`, bundle builds successfully

Then, run application on qtCreator 4.7.0 / Qt 5.11.1 on MacOS
* Application logs:
```
19:42:09: Starting /Users/rcheung/dev/react-qml/examples/WithRedux/build-WithRedux-Desktop_Qt_5_11_1_clang_64bit-Debug/WithRedux.app/Contents/MacOS/WithRedux...
QML debugging is enabled. Only use this in a safe environment.
qrc:/loader_dev.qml:71:9: QML Button: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qml: HMR WebSocker connected: ws://localhost:8081/hot
http://localhost:8081/macos.bundle.js:20829: ReferenceError: RQ is not defined
http://localhost:8081/main.qml?t=1534473730187:13: TypeError: Cannot call method 'init' of undefined
```

### Expected Behavior
Bundle should run with no exceptions.

### Configuration (react-qml.config.js)
```javascript
const path = require('path');

module.exports = ({ root, platform }) => ({
  entry: './main.js',
  output: {
    path: path.join(root, 'qt/dist'),
    filename: `${platform}.bundle.js`,
    library: 'Bundle',
  },
});
```

### Your Environment

MacOS
qtCreator 4.7.0
Qt 5.11.1

| software         | version
| ---------------- | -------
| react-qml-cli        |  `0.2.11`
| react-qml-renderer | `0.2.2`
| qt-react         |  `2.2.13`
| node             | `6.11.5`
| npm or yarn      | `yarn`

**Comment by longseespace** [comment]
Fixed. Also note that `examples` are moved to `/packages`. See https://github.com/longseespace/react-qml/tree/master/packages/example-with-redux.

Please check and let me know if the issue persists

**Comment by cheung31** [comment]
@longseespace Yes, the latest `examples` on `master` now run. Thank you.
